import "./globals.css";
import { App } from "./App";

export const metadata = {
  title: {
    template: 'AniX | %s',
    default: 'AniX',
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <App>{children}</App>
    </html>
  );
}
