import "./globals.css";
import { App } from "./App";
import { ThemeModeScript } from "flowbite-react";

export const metadata = {
  title: {
    template: 'AniX | %s',
    default: 'AniX',
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <App>{children}</App>
    </html>
  );
}
