import "./globals.css";
import { App } from "@/app/App";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <App>{children}</App>
    </html>
  );
}
